routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Support\Facades\Route;
Route::get('/', function () {
    return view('inicio');
});
Route::get('/home', function () {
    return view('home');
});
Route::get('/administracion', function () {
    return view('administracion');
});
Route::get('/publicaciones', function () {
    return view('publicaciones');
});
Route::get('/registro', function () {
    return view('registro');
});
Route::get('/presentacion', function () {
    return view('presentacion');
});
Route::get('/portada', function () {
    return view('portada');
});

Route::get('/blogIndex', function () {
    return view('blogIndex');
});
Route::get('/comunicacionIndex', function () {
    return view('comunicacionIndex');
});

Route::get('/foro', function () {
    return view('foro.index');
});

Route::get('/chat', function () {
    return view('chat.create');
});

Route::get('/noticia.all', function () {
    return view('noticia.all');
});

Route::get('/arte', function () {
    return view('arte.presentacion');
});


Route::get('/formacion', function () {
    return view('formacion.index');
});

Route::get('/investigacion', function () {
    return view('investigacion.index');
});

Route::get('/adminv', function () {
    return view('investigacion.administracion');
});

Route::get('/encuesta', function () {
    return view('encuesta.index');
});

Route::get('/consultas', function () {
    return view('consultas.index');
});

Route::get('/convocatoria', function () {
    return view('convocatoria');
});

Route::get('/configUsu', function () {
    return view('configuracion.administracion');
});

Auth::routes();

Route::get('auth/{provider}', 'Auth\SocialAuthController@redirectToProvider')->name('social.auth');
Route::get('auth/{provider}/callback', 'Auth\SocialAuthController@handleProviderCallback');
Auth::routes();
Route::resource('home', 'HomeController');
Route::get('/social/redirect/{provider}', 'Auth\SocialController@getSocialRedirect')->name('redirectSocialLite');
Route::get('/social/handle/{provider}', 'Auth\SocialController@getSocialHandle')->name('handleSocialLite');
Route::resource('administracion', 'AdministracionController');
Route::resource('presentacion', 'PresentacionController');
Route::resource('presComentario', 'PresComentarioController');
Route::resource('blog', 'BlogsController');
Route::resource('portada', 'PortadaController');
Route::resource('inicio', 'PortadaController');
Route::resource('blogIndex', 'BlogIndexController');
Route::post('blogIndex/store/{id}', 'BlogIndexController@store');


/*Route::get('blogIndex/show/', function(){
     
    /* Nuevo: si el argumento search está vacío regresar a la página anterior */
   
 /*   $search = urlencode(e(Input::get('titulo')));
    dd($search);
    $route = "blogIndex/show/$search";
    return redirect($route);
});*/
Route::get("blogIndex/show/", "BlogIndexController@show");
Route::get('blogIndex/pdf/{id}', 'BlogIndexController@pdf');
Route::get('blogIndex/ppt/{id}', 'BlogIndexController@ppt');
Route::get('blogIndex/docx/{id}', 'BlogIndexController@docx');
Route::get('blogIndex/xlsx/{id}', 'BlogIndexController@xlsx');
Route::get('blogIndex/video/{id}', 'BlogIndexController@video');

Route::resource('comunicacion', 'ComunicacionController');
Route::get('comunicacion/aporte/', 'ComunicacionController@aporte');

Route::resource('comunicacionIndex', 'ComunicacionIndexController');
Route::post('comunicacionIndex/store/{id}', 'ComunicacionIndexController@store');
Route::get("comunicacionIndex/show/", "ComunicacionIndexController@show");

Route::get("comunicacionIndex/content/{id}", "ComunicacionIndexController@content");

Route::resource('foro', 'ForoController');
Route::resource('comentarioForo', 'ComentarioForoController');
Route::post('comentarioForo/store/{id}', 'ComentarioForoController@store');
Route::resource('arte', 'ArteController');

Route::resource('formacion', 'FormacionController');


Route::get('/activo/',[
    'as' => 'foro.activo',
    'uses' => 'ForoController@activo'
]);

Route::get('/cerrado/',[
    'as' => 'foro.cerrado',
    'uses' => 'ForoController@cerrado'
]);
//Route::get('foro/activo/', 'ForoController@activo');

Route::resource('chat', 'ChatsController');

Route::get('/sala/',[
    'as' => 'foro.sala',
    'uses' => 'ForoController@sala'
]);

Route::post('/salachat/',[
    'as' => 'foro.store_chat',
    'uses' => 'ForoController@store_chat'
]);

Route::get('/destroy/',[
    'as' => 'comunicacionIndex.destroy',
    'uses' => 'ComunicacionIndexController@destroy'
]);

Route::get('/comunicacionIndex.administracion/',[
    'as' => 'comunicacionIndex.administracion',
    'uses' => 'ComunicacionIndexController@administracion'
]);

Route::get('/update/{id}',[
    'as' => 'foro.update',
    'uses' => 'ForoController@update'
]);

Route::resource('noticia', 'NoticiasController');

Route::get('/noticia/',[
    'as' => 'noticia.presentacion',
    'uses' => 'NoticiasController@presentacion'
]);

Route::post('/noticia/comentario/',[
    'as' => 'noticia.comentario',
    'uses' => 'NoticiasController@comentario'
]);

Route::get('/noticia/comentario/all/',[
    'as' => 'noticia.allComentario',
    'uses' => 'NoticiasController@allComentario'
]);

Route::get('/noticia/comentario/ver/{id}',[
    'as' => 'noticia.verComentario',
    'uses' => 'NoticiasController@verComentario'
]);

Route::post('/destroyComentario/{id}',[
    'as' => 'noticia.destroyComentario',
    'uses' => 'NoticiasController@destroyComentario'
]);

Route::get('/noticia.index',[
    'as' => 'noticia.index',
    'uses' => 'NoticiasController@index'
]);

Route::get('/noticia.all/',[
    'as' => 'noticia.all',
    'uses' => 'NoticiasController@all'
]);

Route::post('/update/{id}',[
    'as' => 'noticia.update',
    'uses' => 'NoticiasController@update'
]);

Route::get('/noticia.aporte/',[
    'as' => 'noticia.aporte',
    'uses' => 'NoticiasController@aporte'
]);

Route::get('/search/',[
    'as' => 'noticia.search',
    'uses' => 'NoticiasController@search'
]);

Route::get('/mis_noticias/',[
    'as' => 'noticia.mis_noticias',
    'uses' => 'NoticiasController@mis_noticias'
]);

Route::get('/edit_aporte/{id}',[
    'as' => 'noticia.edit_aporte',
    'uses' => 'NoticiasController@edit_aporte'
]);

Route::post('/updateAporte/{id}',[
    'as' => 'noticia.updateAporte',
    'uses' => 'NoticiasController@updateAporte'
]);

Route::get('noticia/pdf/{id}', 'NoticiasController@pdf');
Route::get('noticia/ppt/{id}', 'NoticiasController@ppt');
Route::get('noticia/word/{id}', 'NoticiasController@word');
Route::get('noticia/excel/{id}', 'NoticiasController@excel');
Route::get('noticia/video/{id}', 'NoticiasController@video');

Route::get('/store/{id}',[
    'as' => 'administracion.store',
    'uses' => 'AdministracionController@store'
]);

Route::get('/refreshCaptcha/',[
    'as' => 'noticia.refreshCaptcha',
    'uses' => 'NoticiasController@refreshCaptcha'
]);

Route::get('/arte/',[
    'as' => 'arte.presentacion',
    'uses' => 'ArteController@presentacion'
]);


Route::get('/index',[
    'as' => 'arte.index',
    'uses' => 'ArteController@index'
]);


Route::post('/updateArte/{id}',[
    'as' => 'arte.updateArte',
    'uses' => 'ArteController@updateArte'
]);

Route::get('/misAportes',[
    'as' => 'arte.misAportes',
    'uses' => 'ArteController@misAportes'
]);

Route::get('/ShowMusica',[
    'as' => 'arte.ShowMusica',
    'uses' => 'ArteController@ShowMusica'
]);

Route::get('/ShowDanza',[
    'as' => 'arte.ShowDanza',
    'uses' => 'ArteController@ShowDanza'
]);

Route::get('/ShowPintura',[
    'as' => 'arte.ShowPintura',
    'uses' => 'ArteController@ShowPintura'
]);

Route::get('/ShowOtros',[
    'as' => 'arte.ShowOtros',
    'uses' => 'ArteController@ShowOtros'
]);

Route::get('/ShowChistes',[
    'as' => 'arte.chistes',
    'uses' => 'ArteController@ShowChistes'
]);

Route::get('/pdf/{id}',[
    'as' => 'arte.pdf',
    'uses' => 'ArteController@pdf'
]);

Route::get('/all/',[
    'as' => 'formacion.all',
    'uses' => 'FormacionController@all'
]);

Route::get('/programa/',[
    'as' => 'formacion.programa',
    'uses' => 'FormacionController@administracion'
]);

Route::get('/formacion.aporte/',[
    'as' => 'formacion.aporte',
    'uses' => 'FormacionController@aporte'
]); 

Route::get('/formacion.area/',[
    'as' => 'formacion.area',
    'uses' => 'FormacionController@area'
]); 

Route::get('formacion/pdf/{id}', 'FormacionController@pdf');
Route::get('formacion/ppt/{id}', 'FormacionController@ppt');
Route::get('formacion/word/{id}', 'FormacionController@word');
Route::get('formacion/excel/{id}', 'FormacionController@excel');
Route::get('formacion/video/{id}', 'FormacionController@video');
Route::post('formacion/comentario/{id}', 'FormacionController@comentario');
Route::post('formacion/update/{id}', 'FormacionController@update');

Route::get('/persona/',[
    'as' => 'persona',
    'uses' => 'FormacionController@persona'
]); 
Route::get('/contexto/',[
    'as' => 'contexto',
    'uses' => 'FormacionController@contexto'
]); 
Route::get('/conocimiento/',[
    'as' => 'conocimiento',
    'uses' => 'FormacionController@conocimiento'
]); 
Route::get('/tecnologia/',[
    'as' => 'tecnologia',
    'uses' => 'FormacionController@tecnologia'
]); 
Route::get('/empresa/',[
    'as' => 'empresa',
    'uses' => 'FormacionController@empresa'
]); 

Route::resource('investigacion', 'InvestigacionsController');

Route::get('/show/',[
    'as' => 'investigacion.show',
    'uses' => 'InvestigacionsController@show'
]);

Route::get('/aporte/',[
    'as' => 'investigacion.aporte',
    'uses' => 'InvestigacionsController@aporte'
]);

resources/views/blog.blade.php
@extends('layouts.app')

@section('content')

<!-- Navbar on small screens -->

<!-- Page Container -->
<div class="w3-container w3-content" style="max-width:100%;max-width:1400px;margin-top:8%">    
  <!-- The Grid -->
  <div class="w3-row">
    <!-- Left Column -->
    <div class="w3-col m3">
      <!-- Profile -->
      <div class="w3-card w3-round w3-white">
        <div class="w3-container">
         <h4 class="w3-center">Publicaciones Recientes</h4>
        
         <hr>
         <p><i class="fa fa-pencil fa-fw w3-margin-right w3-text-theme"></i></p>
         <p><i class="fa fa-home fa-fw w3-margin-right w3-text-theme"></i> </p>
         <p><i class="fa fa-birthday-cake fa-fw w3-margin-right w3-text-theme"></i></p>
        </div>
      </div>
      <br>
      
     
      <!-- Interests --> 
      <div class="w3-card w3-round w3-white w3-hide-small">
        <div class="w3-container">
          
        </div>
      </div>
      <br>
      
      <!-- Alert Box -->
      <div class="w3-container w3-display-container w3-round w3-theme-l4 w3-border w3-theme-border w3-margin-bottom w3-hide-small">
        <span onclick="this.parentElement.style.display='none'" class="w3-button w3-theme-l3 w3-display-topright">
          <i class="fa fa-remove"></i>
        </span>
        <p><strong>Alertas</strong></p>
        <p></p>
      </div>
    
    <!-- End Left Column -->
    </div>
    
    <!-- Middle Column -->
    <div class="w3-col m7">
    
      <div class="w3-row-padding">
        <div class="w3-col m12">
          <div class="w3-card w3-round w3-white">
            <div class="w3-container w3-padding">
              <h6 class="w3-opacity">Blog </h6>
                  <a href="{{ route('blog.create') }}" class="btn btn-info" >Nuevo Blog</a>
            </div>
              <br>             
  
<table class="w3-table-all">
<tr>
  <th>Titulo</th>
  <th>Contenido</th>
  <th>Fecha</th>
  <th></th>
  <th></th>
</tr>
@if($blog->count())  
@foreach($blog as $blogs)
<tr>
<td>{{ $blogs-> titulo}}</td>
<td>{{ $blogs-> contenido}}</td>
<td>{{ $blogs-> created_at}}</td>
<td>
        <a class="btn btn-primary btn-xs" class="btn btn-success btn-xs" href="{{action('BlogsController@edit', $blogs->id)}}" type="submit"><span class="glyphicon glyphicon-pencil">
        </span>
      </a>
    </td>
    <td>
     <form action="{{action('BlogsController@destroy', $blogs->id)}}" method="POST">
      {{csrf_field()}}
        <input name="_method" type="hidden" value="DELETE">
        <button class="btn btn-danger btn-xs" type="submit"><span class="glyphicon glyphicon-trash">
        </span>
      </button>
    </td>
</tr>
@endforeach 
               @else
               <tr>
                <td colspan="8">No hay registro !!</td>
              </tr>
              @endif
</table>

          </div>
{{ $blog->links() }}
        </div>
        
      </div>
      
    <!-- End Middle Column -->
    </div>
    
    <!-- Right Column -->
    <div class="w3-col m2">
      <div class="w3-card w3-round w3-white w3-center">
        <div class="w3-container">
          <button type="button" class="w3-button w3-block w3-theme-l4">
            <a href="{{ url('/administracion')}}" class="w3-button-up" title="Messages">Usuarios</a></button>
          <button type="button" class="w3-button w3-block w3-theme-l4"><a href="{{ url('/presentacion')}}" class="w3-button-up" title="Messages">Presentación</a></button>
          <button type="button" class="w3-button w3-block w3-theme-l4" data-toggle="modal" data-target="#myModal">Comentarios</button>
        <button type="button" class="w3-button w3-block w3-theme-l4"><a href="{{ action('BlogsController@presentacion')}}" class="w3-button-up" title="Messages">Presentación</a></button>
        </div>
      </div>
      <br>
    
    <!-- End Right Column -->
    </div>
    
  <!-- End Grid -->
  </div>
  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          
        </div>
        <div class="modal-body">
          


        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>
<!-- End Page Container -->
</div>
<br>

<script type="text/javascript">
  var texto, padre;
$(".contenidoBlog").each(function(){
    texto = $(this).html();
    this.setAttribute("data-texto", texto);
    if ($(this).html().length > 75){
        $(this)
            .html(texto.substr(0, 75) + "...");
    }
});
 

</script>
 
</html> 

resources/views/chart.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>graficos</title>
</head>
<body>
    <div id="pop_div">
<?= $lava->render('LineChart', 'population', 'pop_div') ?>
</div>
</body>
</html>

resources/views/comunicacionAporte.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        
            <div class="card">
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <div class="w3-container w3-content" style="max-width:100%;max-width:1400px;margin-top:12%">    
  <!-- The Grid -->
  <div class="w3-row">
    <!-- Left Column -->
    <div class="w3-col m3">
      <!-- Profile -->
      <div class="w3-card w3-round w3-white">


      <div class="w3-card w3-round w3-white">
        <div class="w3-container">
          
        </div>
      </div>    

      </div>
      <br>   
    <!-- End Left Column -->
    </div>
    
    <!-- Middle Column -->
    <div class="w3-col m7">
    
      <div class="w3-row-padding .w3-padding-blog">
              <h6 class="w3-opacity">Comunicacion </h6>
<table class="w3-table-all">
<tr>
  <th>Titulo</th>
  <th>Eje</th>
  <th>Fecha</th>
  <th></th>
  <th></th>
</tr>
@if($comunicacion->count())  
@foreach($comunicacion as $comunicacions)
<tr>
<td>{{ $comunicacions-> titulo }}</td>
<td> {{ $comunicacions-> eje }}</td>
<td>{{ $comunicacions-> created_at }}</td>
<td>
        <a class="btn btn-primary btn-xs" class="btn btn-success btn-xs" href="{{action('ComunicacionIndexController@content', $comunicacions->id)}}" type="submit"><span class="glyphicon glyphicon-pencil">
        </span>
      </a>
    </td>
    <td>
     <form action="{{action('ComunicacionController@destroy', $comunicacions->id)}}" method="POST">
      {{csrf_field()}}
        <input name="_method" type="hidden" value="DELETE">
        <button class="btn btn-danger btn-xs" type="submit"><span class="glyphicon glyphicon-trash">
        </span>
      </button>
    </td>
</tr>
@endforeach 
               @else
               <tr>
                <td colspan="8">No hay registro !!</td>
              </tr>
              @endif
</table>
{{ $comunicacion->links() }}
          </div>
            <a href="{{ route('comunicacionIndex.index') }}" class="w3-button-up" title="Messages"><span class="glyphicon glyphicon-backward">
        </span>Atrás</a>
      </div>

<br>

   
    <!-- End Middle Column -->
    </div>
    
    <!-- Right Column -->
    <div class="w3-col m2">
      <div class="w3-card w3-round w3-white w3-center">
<div class="w3-container">
</div>
      </div>
      <br>
    
    <!-- End Right Column -->
    </div>
    
  <!-- End Grid -->
  </div>
  
<!-- End Page Container -->
</div>
                </div>
            </div>
        
    </div>
</div>

@endsection

resources/views/comunicacionIndex.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        
            <div class="card">
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <div class="w3-container w3-content" style="max-width:100%;max-width:1400px;margin-top:12%">    
  <!-- The Grid -->
  <div class="w3-row">
    <!-- Left Column -->
    <div class="w3-col m3">
      <!-- Profile -->
      <div class="w3-card w3-round w3-white">
        <div class="w3-container">
         <h4 class="w3-center"></h4>
        <form method="GET" action="{{action('ComunicacionIndexController@show')}}"  role="form" enctype="multipart/form-data">
              {{ csrf_field() }}
         <p>Buscar por título</p>
         <p><input type="text" name="titulo" class="form-control input-sm"></p>
                         <div class="col-xs-12 col-sm-12 col-md-12">
                  <input type="submit"  value="Buscar" class="w3-button w3-theme-d2 w3-margin-bottom">
                  </div>
         </form>
         <p><i class="fa fa-birthday-cake fa-fw w3-margin-right w3-text-theme"></i></p>
        </div>

      <div class="w3-card w3-round w3-white">
        <div class="w3-container">
          <button type="button" class="w3-button w3-block w3-theme-l4">
            <a href="{{ route('comunicacion.nuevaComunicacion')}}" class="w3-button-up" title="Messages">Nueva +</a></button>
          <button type="button" class="w3-button w3-block w3-theme-l4">
            <a href="{{ route('comunicacionIndex.create') }}" class="w3-button-up" title="Messages">Mis Aportes</a></button>
          <button type="button" class="w3-button w3-block w3-theme-l4">
            <a href="{{ url('/foro') }}" class="w3-button-up" title="Messages">Eventos</a></button>
<button type="button" class="w3-button w3-block w3-theme-l4">
            <a href="{{ url('/comunicacionIndex') }}" class="w3-button-up" title="Messages">Atrás</a></button>
        </div>
      </div>    

      </div>
      <br>   
    <!-- End Left Column -->
    </div>
    
    <!-- Middle Column -->
    <div class="w3-col m7">
    
      <div class="w3-row-padding .w3-padding-blog">
        @if($comunicacion->count())  
        @foreach($comunicacion as $comunicacions)
        <div class="w3-col m12">
          <div class="w3-card w3-round w3-white">
            <div id="presentacion" class="w3-container">
            <h2>{{ $comunicacions->  created_at}}</h2>
            <i style="color:#BDBDBD;">{{ $comunicacions-> name }}</i>
            <h2><i>{{ $comunicacions->  titulo}}</i></h2>


          
          <a href="{{action('ComunicacionIndexController@edit', $comunicacions->id)}}" ><i style="color: blue;"> Ver más +</i></a>
<br>
            </div>
          </div>
             <br>
        </div>
    @endforeach 
    @endif

      </div>

                  <div class="w3-row-padding">
        <div class="w3-col m12">
          <div class="w3-card w3-round w3-white">
            <div id="presentacion" class="w3-container w3-padding">
  <div class="w3-content" style="max-width:700px">
    <p>Comentarios</p>
    
<form method="POST" action="{{action('ComunicacionController@comentario')}}"  role="form">
              {{ csrf_field() }}
      <p><input type="hidden" name="_token" value="<?php echo csrf_token(); ?>">
        <p>Nombre</p>
        <p><input class="w3-input w3-padding-16 w3-border" type="text"  name="nombre" id="nombre" required value=""></p>
        <p>Apellido</p>
        <p><input class="w3-input w3-padding-16 w3-border" type="text"  name="apellido" id="apellido" required value=""></p>
        <p>Correo electrónico</p>
        <p><input class="w3-input w3-padding-16 w3-border" type="text"  name="email" id="email" required value=""></p>
        <p>Deja tu comentario</p>
        <input class="w3-input w3-padding-16 w3-border" type="text"  name="comentario" id="comentario" required value=""></p>
      <button class="w3-button w3-theme-d2 w3-margin-bottom" type="submit">Enviar</button></p>
    </form>

    </div>
            </div>
          </div>
        </div>
      </div>
         <br>
   
   @if($c->count())  
@foreach($c as $c)
      <div class="w3-row-padding">

        <div class="w3-col m12">
          <div class="w3-card w3-round w3-white">
            <div id="presentacion" class="w3-container w3-padding">
  <div class="w3-content" style="max-width:700px">



  <p>{{ $c-> nombre}}</p>
  <p>{{ $c-> email}}</p>
  <p>{{ $c-> comentario}}</p>
  <p>{{ $c-> created_at}}</p>


    </div>
            </div>
          </div>
        </div>

      </div>
    </br>

            @endforeach 
@else
              <div>
                <p>No hay comentarios !!</p>
            
              @endif  
              </div>

      </div>
<br>
   
    <!-- End Middle Column -->
    </div>
    
    <!-- Right Column -->
    <div class="w3-col m2">
      <div class="w3-card w3-round w3-white w3-center">
<div class="w3-container">
</div>
      </div>
      <br>
    
    <!-- End Right Column -->
    </div>
    
  <!-- End Grid -->
  </div>
  
<!-- End Page Container -->
</div>
                </div>
            </div>
        
    </div>
</div>
<script type="text/javascript">
  var texto, padre;
$(".contenidoBlog").each(function(){
    texto = $(this).html();
    this.setAttribute("data-texto", texto);
    if ($(this).html().length > 75){
        $(this)
            .html(texto.substr(0, 75) + "...");
    }
});
 

</script>
@endsection

resources/views/comunicacionPresentacion.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        
            <div class="card">
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <div class="w3-container w3-content" style="max-width:100%;max-width:1400px;margin-top:12%">    
  <!-- The Grid -->
  <div class="w3-row">
    <!-- Left Column -->
    <div class="w3-col m3">
      <!-- Profile -->
      <div class="w3-card w3-round w3-white">
        <div class="w3-container">
         <h4 class="w3-center"></h4>
         <p><i class="fa fa-birthday-cake fa-fw w3-margin-right w3-text-theme"></i></p>
        </div>

      <div class="w3-card w3-round w3-white">
        <div class="w3-container">
            <button type="button" class="w3-button w3-block w3-theme-l4">
            <a href="{{ route('comunicacionIndex.destroy')}}" class="w3-button-up" title="Messages">Todas las comunicaciones</a></button>
          <button type="button" class="w3-button w3-block w3-theme-l4">
            <a href="{{ route('comunicacion.nuevaComunicacion')}}" class="w3-button-up" title="Messages">Nueva Comunicación</a></button>
          <button type="button" class="w3-button w3-block w3-theme-l4">
            <a href="{{ route('comunicacionIndex.create') }}" class="w3-button-up" title="Messages">Mis Aportes</a></button>
          <button type="button" class="w3-button w3-block w3-theme-l4">
            <a href="{{ url('/foro') }}" class="w3-button-up" title="Messages">Eventos</a></button>
        </div>
      </div>    

      </div>
      <br>   
    <!-- End Left Column -->
    </div>
    
    <!-- Middle Column -->
    <div class="w3-col m7">
    
      <div class="w3-row-padding .w3-padding-blog">
        
        <div class="w3-col m12">
          <div class="w3-card w3-round w3-white">
            <div id="presentacion" class="w3-container">
            {{ $comunicacion -> contenido }}
            </div>
          </div>
             <br>
        </div>


      </div>

<br>

   
    <!-- End Middle Column -->
    </div>
    
    <!-- Right Column -->
    <div class="w3-col m2">
      <div class="w3-card w3-round w3-white w3-center">
<div class="w3-container">
</div>
      </div>
      <br>
    
    <!-- End Right Column -->
    </div>
    
  <!-- End Grid -->
  </div>
  
<!-- End Page Container -->
</div>
                </div>
            </div>
        
    </div>
</div>
<script type="text/javascript">
  var texto, padre;
$(".contenidoBlog").each(function(){
    texto = $(this).html();
    this.setAttribute("data-texto", texto);
    if ($(this).html().length > 75){
        $(this)
            .html(texto.substr(0, 75) + "...");
    }
});
 

</script>
@endsection