routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Support\Facades\Route;
Route::get('/', function () {
    return view('inicio');
});
Route::get('/home', function () {
    return view('home');
});
Route::get('/administracion', function () {
    return view('administracion');
});
Route::get('/publicaciones', function () {
    return view('publicaciones');
});
Route::get('/registro', function () {
    return view('registro');
});
Route::get('/presentacion', function () {
    return view('presentacion');
});
Route::get('/portada', function () {
    return view('portada');
});

Route::get('/blogIndex', function () {
    return view('blogIndex');
});
Route::get('/comunicacionIndex', function () {
    return view('comunicacionIndex');
});

Route::get('/foro', function () {
    return view('foro.index');
});

Route::get('/chat', function () {
    return view('chat.create');
});

Route::get('/noticia.all', function () {
    return view('noticia.all');
});

Route::get('/arte', function () {
    return view('arte.presentacion');
});


Route::get('/formacion', function () {
    return view('formacion.index');
});

Route::get('/investigacion', function () {
    return view('investigacion.index');
});

Route::get('/adminv', function () {
    return view('investigacion.administracion');
});

Route::get('/encuesta', function () {
    return view('encuesta.index');
});

Route::get('/consultas', function () {
    return view('consultas.index');
});

Route::get('/convocatoria', function () {
    return view('convocatoria');
});

Route::get('/configUsu', function () {
    return view('configuracion.administracion');
});

Auth::routes();

Route::get('auth/{provider}', 'Auth\SocialAuthController@redirectToProvider')->name('social.auth');
Route::get('auth/{provider}/callback', 'Auth\SocialAuthController@handleProviderCallback');
Auth::routes();
Route::resource('home', 'HomeController');
Route::get('/social/redirect/{provider}', 'Auth\SocialController@getSocialRedirect')->name('redirectSocialLite');
Route::get('/social/handle/{provider}', 'Auth\SocialController@getSocialHandle')->name('handleSocialLite');
Route::resource('administracion', 'AdministracionController');
Route::resource('presentacion', 'PresentacionController');
Route::resource('presComentario', 'PresComentarioController');
Route::resource('blog', 'BlogsController');
Route::resource('portada', 'PortadaController');
Route::resource('inicio', 'PortadaController');
Route::resource('blogIndex', 'BlogIndexController');
Route::post('blogIndex/store/{id}', 'BlogIndexController@store');


/*Route::get('blogIndex/show/', function(){
     
    /* Nuevo: si el argumento search está vacío regresar a la página anterior */
   
 /*   $search = urlencode(e(Input::get('titulo')));
    dd($search);
    $route = "blogIndex/show/$search";
    return redirect($route);
});*/
Route::get("blogIndex/show/", "BlogIndexController@show");
Route::get('blogIndex/pdf/{id}', 'BlogIndexController@pdf');
Route::get('blogIndex/ppt/{id}', 'BlogIndexController@ppt');
Route::get('blogIndex/docx/{id}', 'BlogIndexController@docx');
Route::get('blogIndex/xlsx/{id}', 'BlogIndexController@xlsx');
Route::get('blogIndex/video/{id}', 'BlogIndexController@video');

Route::resource('comunicacion', 'ComunicacionController');
Route::get('comunicacion/aporte/', 'ComunicacionController@aporte');

Route::resource('comunicacionIndex', 'ComunicacionIndexController');
Route::post('comunicacionIndex/store/{id}', 'ComunicacionIndexController@store');
Route::get("comunicacionIndex/show/", "ComunicacionIndexController@show");

Route::get("comunicacionIndex/content/{id}", "ComunicacionIndexController@content");

Route::resource('foro', 'ForoController');
Route::resource('comentarioForo', 'ComentarioForoController');
Route::post('comentarioForo/store/{id}', 'ComentarioForoController@store');
Route::resource('arte', 'ArteController');

Route::resource('formacion', 'FormacionController');


Route::get('/activo/',[
    'as' => 'foro.activo',
    'uses' => 'ForoController@activo'
]);

Route::get('/cerrado/',[
    'as' => 'foro.cerrado',
    'uses' => 'ForoController@cerrado'
]);
//Route::get('foro/activo/', 'ForoController@activo');

Route::resource('chat', 'ChatsController');

Route::get('/sala/',[
    'as' => 'foro.sala',
    'uses' => 'ForoController@sala'
]);

Route::post('/salachat/',[
    'as' => 'foro.store_chat',
    'uses' => 'ForoController@store_chat'
]);

Route::get('/destroy/',[
    'as' => 'comunicacionIndex.destroy',
    'uses' => 'ComunicacionIndexController@destroy'
]);

Route::get('/comunicacionIndex.administracion/',[
    'as' => 'comunicacionIndex.administracion',
    'uses' => 'ComunicacionIndexController@administracion'
]);

Route::get('/update/{id}',[
    'as' => 'foro.update',
    'uses' => 'ForoController@update'
]);

Route::resource('noticia', 'NoticiasController');

Route::get('/noticia/',[
    'as' => 'noticia.presentacion',
    'uses' => 'NoticiasController@presentacion'
]);

Route::post('/noticia/comentario/',[
    'as' => 'noticia.comentario',
    'uses' => 'NoticiasController@comentario'
]);

Route::get('/noticia/comentario/all/',[
    'as' => 'noticia.allComentario',
    'uses' => 'NoticiasController@allComentario'
]);

Route::get('/noticia/comentario/ver/{id}',[
    'as' => 'noticia.verComentario',
    'uses' => 'NoticiasController@verComentario'
]);

Route::post('/destroyComentario/{id}',[
    'as' => 'noticia.destroyComentario',
    'uses' => 'NoticiasController@destroyComentario'
]);

Route::get('/noticia.index',[
    'as' => 'noticia.index',
    'uses' => 'NoticiasController@index'
]);

Route::get('/noticia.all/',[
    'as' => 'noticia.all',
    'uses' => 'NoticiasController@all'
]);

Route::post('/update/{id}',[
    'as' => 'noticia.update',
    'uses' => 'NoticiasController@update'
]);

Route::get('/noticia.aporte/',[
    'as' => 'noticia.aporte',
    'uses' => 'NoticiasController@aporte'
]);

Route::get('/search/',[
    'as' => 'noticia.search',
    'uses' => 'NoticiasController@search'
]);

Route::get('/mis_noticias/',[
    'as' => 'noticia.mis_noticias',
    'uses' => 'NoticiasController@mis_noticias'
]);

Route::get('/edit_aporte/{id}',[
    'as' => 'noticia.edit_aporte',
    'uses' => 'NoticiasController@edit_aporte'
]);

Route::post('/updateAporte/{id}',[
    'as' => 'noticia.updateAporte',
    'uses' => 'NoticiasController@updateAporte'
]);

Route::get('noticia/pdf/{id}', 'NoticiasController@pdf');
Route::get('noticia/ppt/{id}', 'NoticiasController@ppt');
Route::get('noticia/word/{id}', 'NoticiasController@word');
Route::get('noticia/excel/{id}', 'NoticiasController@excel');
Route::get('noticia/video/{id}', 'NoticiasController@video');

Route::get('/store/{id}',[
    'as' => 'administracion.store',
    'uses' => 'AdministracionController@store'
]);

Route::get('/refreshCaptcha/',[
    'as' => 'noticia.refreshCaptcha',
    'uses' => 'NoticiasController@refreshCaptcha'
]);

Route::get('/arte/',[
    'as' => 'arte.presentacion',
    'uses' => 'ArteController@presentacion'
]);


Route::get('/index',[
    'as' => 'arte.index',
    'uses' => 'ArteController@index'
]);


Route::post('/updateArte/{id}',[
    'as' => 'arte.updateArte',
    'uses' => 'ArteController@updateArte'
]);

Route::get('/misAportes',[
    'as' => 'arte.misAportes',
    'uses' => 'ArteController@misAportes'
]);

Route::get('/ShowMusica',[
    'as' => 'arte.ShowMusica',
    'uses' => 'ArteController@ShowMusica'
]);

Route::get('/ShowDanza',[
    'as' => 'arte.ShowDanza',
    'uses' => 'ArteController@ShowDanza'
]);

Route::get('/ShowPintura',[
    'as' => 'arte.ShowPintura',
    'uses' => 'ArteController@ShowPintura'
]);

Route::get('/ShowOtros',[
    'as' => 'arte.ShowOtros',
    'uses' => 'ArteController@ShowOtros'
]);

Route::get('/ShowChistes',[
    'as' => 'arte.chistes',
    'uses' => 'ArteController@ShowChistes'
]);

Route::get('/pdf/{id}',[
    'as' => 'arte.pdf',
    'uses' => 'ArteController@pdf'
]);

Route::get('/all/',[
    'as' => 'formacion.all',
    'uses' => 'FormacionController@all'
]);

Route::get('/programa/',[
    'as' => 'formacion.programa',
    'uses' => 'FormacionController@administracion'
]);

Route::get('/formacion.aporte/',[
    'as' => 'formacion.aporte',
    'uses' => 'FormacionController@aporte'
]); 

Route::get('/formacion.area/',[
    'as' => 'formacion.area',
    'uses' => 'FormacionController@area'
]); 

Route::get('formacion/pdf/{id}', 'FormacionController@pdf');
Route::get('formacion/ppt/{id}', 'FormacionController@ppt');
Route::get('formacion/word/{id}', 'FormacionController@word');
Route::get('formacion/excel/{id}', 'FormacionController@excel');
Route::get('formacion/video/{id}', 'FormacionController@video');
Route::post('formacion/comentario/{id}', 'FormacionController@comentario');
Route::post('formacion/update/{id}', 'FormacionController@update');

Route::get('/persona/',[
    'as' => 'persona',
    'uses' => 'FormacionController@persona'
]); 
Route::get('/contexto/',[
    'as' => 'contexto',
    'uses' => 'FormacionController@contexto'
]); 
Route::get('/conocimiento/',[
    'as' => 'conocimiento',
    'uses' => 'FormacionController@conocimiento'
]); 
Route::get('/tecnologia/',[
    'as' => 'tecnologia',
    'uses' => 'FormacionController@tecnologia'
]); 
Route::get('/empresa/',[
    'as' => 'empresa',
    'uses' => 'FormacionController@empresa'
]); 

Route::resource('investigacion', 'InvestigacionsController');

Route::get('/show/',[
    'as' => 'investigacion.show',
    'uses' => 'InvestigacionsController@show'
]);

Route::get('/aporte/',[
    'as' => 'investigacion.aporte',
    'uses' => 'InvestigacionsController@aporte'
]);

app/Comunicacion.php
<?php

namespace App;
 
use Illuminate\Database\Eloquent\Model;

class Comunicacion extends Model
{
        protected $fillable = [
        'titulo', 'comunicado', 'eje', 'id_usuario'
    ];
}

app/Http/Controllers/ComunicacionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Comunicacion;
use App\Ejes;
use App\ComenComunicacion;
use App\Contenidos;

class ComunicacionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

    $comunicacion = Comunicacion::orderBy('id', 'DESC')->paginate(15);
    return view('comunicacion.index')->with ('comunicacion', $comunicacion);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $eje = Ejes::all('id', 'descripcion')->pluck('descripcion', 'descripcion');
        return \View::make('comunicacion.crear', compact('eje'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $comunicacion = new Comunicacion();
        $comunicacion->titulo = $request->titulo;
        $comunicacion->comunicado = $request->comunicacion;
        $comunicacion->eje = $request->eje;
        $comunicacion->id_usuario = auth()->id();
                $request->validate([

            'captcha' => 'required|captcha'
        ]);

        $success = $comunicacion->save() ? $request->session()->flash('success', '¡Registro exitoso!') : $request->session()->flash('success', 'Ooops! Algo salio mal :(');

        $comunicacion = Comunicacion::orderBy('id', 'DESC')->paginate(15);
        return view('comunicacionIndex')->with ('comunicacion', $comunicacion);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
               $comunicacion = Comunicacion::where('id_usuario','=', auth()->id())->paginate(10);
               return view('comunicacion.aporte')
               ->with('comunicacion', $comunicacion);   
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $comunicacion=Comunicacion::find($id);
        $eje = Ejes::all('id', 'descripcion')->pluck('descripcion', 'descripcion');
        
        return view('comunicacion.editar') 
        ->with('comunicacion', $comunicacion)
        ->with('eje', $eje);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[ 'titulo'=>'required', 'comunicado'=>'required', 'eje'=>'required']);

       Comunicacion::find($id)->update($request->all());


        return redirect()->route('comunicacion.index')->with('success','Registro actualizado satisfactoriamente');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Comunicacion::find($id)->delete();
        return redirect()->route('comunicacion.index')->with('success','Registro eliminado satisfactoriamente');
    }

        public function aporte()
    {
 
        
        return view('comunicacion.show'); 
        
    }

    public function comentario(Request $request)
    {
        $c = new ComenComunicacion();
        $c->nombre = $request->nombre;
        $c->apellido = $request->apellido;
        $c->email = $request->email;
        $c->comentario = $request->comentario;

       if($c->save()){
            return redirect()->route('comunicacion.index')->with('success-message', 'File has been uploaded');
        }else{
            return redirect('uploads')->with('error-message', 'An error ocurred saving data into database');
        } 
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function showComentarios()
    {
    $comen = ComenComunicacion::orderBy('id', 'DESC')->paginate(15);
    return view('comunicacion.comentarios')->with ('comen', $comen);
    }

        public function nuevaComunicacion()
    {
        $eje = Ejes::all('id', 'descripcion')->pluck('descripcion', 'descripcion');
        return \View::make('comunicacion.nuevaComunicacion', compact('eje'));
    }

        public function presentacion()
    {
        $id = 1;
       $comunicacion=Contenidos::find($id);        
        return view('comunicacion.presentacion')->with ('comunicacion', $comunicacion);
    }

    public function updatePresentacion(Request $request, $id)
    {
        $this->validate($request,[ 'contenido'=>'required']);

       Contenidos::find($id)->update($request->all());


        return redirect()->route('comunicacion.index')->with('success','Registro actualizado satisfactoriamente');
    }
}

resources/views/comunicacion/aporte.blade.php
@extends('layouts.app')

@section('content')

<!-- Navbar on small screens -->

<!-- Page Container -->
<div class="w3-container w3-content" style="max-width:100%;max-width:1400px;margin-top:8%">    
  <!-- The Grid -->
  <div class="w3-row">
    <!-- Left Column -->
    <div class="w3-col m3">
      <!-- Profile -->
      <div class="w3-card w3-round w3-white">

      </div>
      <br>
      
     

      <br>

    
    <!-- End Left Column -->
    </div>
    
    <!-- Middle Column -->
    <div class="w3-col m7">
    
      <div class="w3-row-padding">
        <div class="w3-col m12">
          <div class="w3-card w3-round w3-white">
            <div class="w3-container w3-padding">
              <h6 class="w3-opacity">Comunicacion </h6>
            </div>
              <br>             
  
<table class="w3-table-all">
<tr>
  <th>Titulo</th>
  <th>Eje</th>
  <th>Fecha</th>
  <th></th>
  <th></th>
</tr>
@if($comunicacion->count())  
@foreach($comunicacion as $comunicacions)
<tr>
<td>{{ $comunicacions-> titulo }}</td>
<td> {{ $comunicacions-> eje }}</td>
<td>{{ $comunicacions-> created_at }}</td>
<td>
        <a class="btn btn-primary btn-xs" class="btn btn-success btn-xs" href="{{action('ComunicacionController@edit', $comunicacions->id)}}" type="submit"><span class="glyphicon glyphicon-pencil">
        </span>
      </a>
    </td>
    <td>
     <form action="{{action('ComunicacionController@destroy', $comunicacions->id)}}" method="POST">
      {{csrf_field()}}
        <input name="_method" type="hidden" value="DELETE">
        <button class="btn btn-danger btn-xs" type="submit"><span class="glyphicon glyphicon-trash">
        </span>
      </button>
    </td>
</tr>
@endforeach 
               @else
               <tr>
                <td colspan="8">No hay registro !!</td>
              </tr>
              @endif
</table>

          </div>
          {{ $comunicacion->links() }}
        </div>
        
      </div>
      
    <!-- End Middle Column -->
    </div>
    
    <!-- Right Column -->
    <div class="w3-col m2">
      <div class="w3-card w3-round w3-white w3-center">
        <div class="w3-container w3-padding">
          <button type="button" class="w3-button w3-block w3-theme-l4">
            <a href="{{ route('comunicacion.create')}}" class="w3-button-up" title="Messages">Nueva comunicación</a></button>
          
        </div>
      </div>
      <br>
    
    <!-- End Right Column -->
    </div>
    
  <!-- End Grid -->
  </div>
  <!-- Modal -->

<!-- End Page Container -->
</div>
<br>


</script>
 
</html> 

resources/views/comunicacion/crear.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        
            <div class="card">
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <div class="w3-container w3-content" style="max-width:100%;max-width:1400px;margin-top:12%">    
  <!-- The Grid -->
  <div class="w3-row">
    <!-- Left Column -->
    <div class="w3-col m3">
      <!-- Profile -->
      <div class="w3-card w3-round w3-white">


      <div class="w3-card w3-round w3-white">
        <div class="w3-container">
          
        </div>
      </div>    

      </div>
      <br>   
    <!-- End Left Column -->
    </div>
    
    <!-- Middle Column -->
    <div class="w3-col m7">
    
      <div class="w3-row-padding .w3-padding-blog">

      @if (count($errors) > 0)
      <div class="alert alert-danger">
        <strong>Error!</strong> Revise los campos obligatorios.<br><br>
        <ul>
          @foreach ($errors->all() as $error)
          <li>{{ $error }}</li>
          @endforeach
        </ul>
      </div>
      @endif
      @if(Session::has('success'))
      <div class="alert alert-info">
        {{Session::get('success')}}
      </div>
      @endif

                <div class="table-container">
            <form method="POST" action="{{ route('comunicacion.store') }}"  role="form">
              {{ csrf_field() }}
 
              <div class="form-group">
                <textarea name="titulo" id="titulo" class="form-control input-sm" placeholder="Título"></textarea>
              </div>
              <div class="form-group">
                    <textarea name="comunicacion" id="comunicacion" class="form-control input-sm" maxlength="2000" rows="5" placeholder="Comunicación"></textarea>
              </div>
              <p>Eje de la actividad académica universitaria</p>

              {!! Form::select('eje', $eje, null, ['class' => 'form-control'] ) !!}

              <br>
                        <div class="row">
          <div class="col-md-4"></div>
          <div class="form-group col-md-4">
             <div class="captcha">
               <span>{!! captcha_img('flat') !!}</span>

               </div>
            </div>
        </div>
        <div class="row">
          <div class="col-md-4"></div>
            <div class="form-group col-md-4">
             <input id="captcha" type="text" class="form-control" placeholder="Enter Captcha" name="captcha"></div>
          </div>
 
                <div class="col-xs-12 col-sm-12 col-md-12">
                  <input type="submit"  value="Guardar" class="btn btn-success btn-block">
                  <a href="{{ route('comunicacion.index') }}" class="btn btn-info btn-block" > Atrás</a></div>
            </form>
          </div>

      </div>

<br>

   
    <!-- End Middle Column -->
    </div>
    
    <!-- Right Column -->
    <div class="w3-col m2">
      <div class="w3-card w3-round w3-white w3-center">
<div class="w3-container">
</div>
      </div>
      <br>
    
    <!-- End Right Column -->
    </div>
    
  <!-- End Grid -->
  </div>
  
<!-- End Page Container -->
</div>
                </div>
            </div>
        
    </div>
</div>

@endsection

resources/views/comunicacion/editar.blade.php
@extends('layouts.app')

@section('content')

<!-- Navbar on small screens -->

<!-- Page Container -->
<div class="w3-container w3-content" style="max-width:100%;max-width:1400px;margin-top:8%">    
  <!-- The Grid -->
  <div class="w3-row">
    <!-- Left Column -->
    <div class="w3-col m3">
      <!-- Profile -->
      <div class="w3-card w3-round w3-white">

      </div>
      <br>
      
     

      
      <!-- Alert Box -->
    
    <!-- End Left Column -->
    </div>
    
    <!-- Middle Column -->
    <div class="w3-col m7">
    
      <div class="w3-row-padding">
        <div class="w3-col m12">
          <div class="w3-card w3-round w3-white">
            <div class="w3-container w3-padding">
      @if (count($errors) > 0)
      <div class="alert alert-danger">
        <strong>Error!</strong> Revise los campos obligatorios.<br><br>
        <ul>
          @foreach ($errors->all() as $error)
          <li>{{ $error }}</li>
          @endforeach
        </ul>
      </div>
      @endif
      @if(Session::has('success'))
      <div class="alert alert-info">
        {{Session::get('success')}}
      </div>
      @endif

      <form method="POST" action="{{ route('comunicacion.update',$comunicacion->id) }}"  role="form" enctype="multipart/form-data">
              {{ csrf_field() }}
              <p>Título</p>
              <input name="_method" type="hidden" value="PATCH">
               <div class="form-group">
                <textarea name="titulo" class="form-control input-sm"  placeholder="Titulo">{{$comunicacion->titulo}}</textarea>
              </div>
              <p>Contenido</p>
              <div class="form-group">
                <textarea rows="15" cols="50" maxlength="2000" name="comunicado" class="form-control input-sm" rows="5"  placeholder="Comunicacion">{{$comunicacion->comunicado}}</textarea>
              </div>
            <p>Eje de la actividad académaica universitaria</p>
            {!! Form::select('eje', $eje, null, ['class' => 'form-control'] ) !!}
          <div class="plan-name-bronze">
            
          </div>
            </br>


              </br>
              <div class="row">
 
                <div class="col-xs-12 col-sm-12 col-md-12">
                  <input type="submit"  value="Actualizar" class="w3-button w3-theme-d2 w3-margin-bottom">
                </div>  
 
              </div>
            </form>



        </div>
          </div>
        </div>
        
      </div>
<br>

      
    <!-- End Middle Column -->
    </div>
    
    <!-- Right Column -->
    <div class="w3-col m2">

    
    <!-- End Right Column -->
    </div>
    
  <!-- End Grid -->
  </div>
  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          
        </div>
        <div class="modal-body">
          


        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>
<!-- End Page Container -->
</div>
<br>
 
</html> 

resources/views/comunicacion/nuevaComunicacion.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        
            <div class="card">
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <div class="w3-container w3-content" style="max-width:100%;max-width:1400px;margin-top:12%">    
  <!-- The Grid -->
  <div class="w3-row">
    <!-- Left Column -->
    <div class="w3-col m3">
      <!-- Profile -->
      <div class="w3-card w3-round w3-white">


      <div class="w3-card w3-round w3-white">
        <div class="w3-container">
          
        </div>
      </div>    

      </div>
      <br>   
    <!-- End Left Column -->
    </div>
    
    <!-- Middle Column -->
    <div class="w3-col m7">
    
      <div class="w3-row-padding .w3-padding-blog">

      @if (count($errors) > 0)
      <div class="alert alert-danger">
        <strong>Error!</strong> Revise los campos obligatorios.<br><br>
        <ul>
          @foreach ($errors->all() as $error)
          <li>{{ $error }}</li>
          @endforeach
        </ul>
      </div>
      @endif
      @if(Session::has('success'))
      <div class="alert alert-info">
        {{Session::get('success')}}
      </div>
      @endif

                <div class="table-container">
            <form method="POST" action="{{ route('comunicacion.store') }}"  role="form">
              {{ csrf_field() }}
 
              <div class="form-group">
                <textarea name="titulo" id="titulo" class="form-control input-sm" placeholder="Título"></textarea>
              </div>
              <div class="form-group">
                    <textarea name="comunicacion" id="comunicacion" class="form-control input-sm" maxlength="2000" rows="5" placeholder="Comunicación"></textarea>
              </div>
              <p>Eje de la actividad académica universitaria</p>

              {!! Form::select('eje', $eje, null, ['class' => 'form-control'] ) !!}

              <br>
                        <div class="row">
          <div class="col-md-4"></div>
          <div class="form-group col-md-4">
             <div class="captcha">
               <span>{!! captcha_img('flat') !!}</span>

               </div>
            </div>
        </div>
        <div class="row">
          <div class="col-md-4"></div>
            <div class="form-group col-md-4">
             <input id="captcha" type="text" class="form-control" placeholder="Enter Captcha" name="captcha"></div>
          </div>
 
                <div class="col-xs-12 col-sm-12 col-md-12">
                  <input type="submit"  value="Guardar" class="btn btn-success btn-block">
                  <a href="{{ url('/comunicacionIndex') }}" class="btn btn-info btn-block" > Atrás</a></div>
            </form>
          </div>

      </div>

<br>

   
    <!-- End Middle Column -->
    </div>
    
    <!-- Right Column -->
    <div class="w3-col m2">
      <div class="w3-card w3-round w3-white w3-center">
<div class="w3-container">
</div>
      </div>
      <br>
    
    <!-- End Right Column -->
    </div>
    
  <!-- End Grid -->
  </div>
  
<!-- End Page Container -->
</div>
                </div>
            </div>
        
    </div>
</div>

@endsection