routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Support\Facades\Route;
Route::get('/', function () {
    return view('inicio');
});
Route::get('/home', function () {
    return view('home');
});
Route::get('/administracion', function () {
    return view('administracion');
});
Route::get('/publicaciones', function () {
    return view('publicaciones');
});
Route::get('/registro', function () {
    return view('registro');
});
Route::get('/presentacion', function () {
    return view('presentacion');
});
Route::get('/portada', function () {
    return view('portada');
});

Route::get('/blogIndex', function () {
    return view('blogIndex');
});
Route::get('/comunicacionIndex', function () {
    return view('comunicacionIndex');
});

Route::get('/foro', function () {
    return view('foro.index');
});

Route::get('/chat', function () {
    return view('chat.create');
});

Route::get('/noticia.all', function () {
    return view('noticia.all');
});

Route::get('/arte', function () {
    return view('arte.presentacion');
});


Route::get('/formacion', function () {
    return view('formacion.index');
});

Route::get('/investigacion', function () {
    return view('investigacion.index');
});

Route::get('/adminv', function () {
    return view('investigacion.administracion');
});

Route::get('/encuesta', function () {
    return view('encuesta.index');
});

Route::get('/consultas', function () {
    return view('consultas.index');
});

Route::get('/convocatoria', function () {
    return view('convocatoria');
});

Route::get('/configUsu', function () {
    return view('configuracion.administracion');
});

Auth::routes();

Route::get('auth/{provider}', 'Auth\SocialAuthController@redirectToProvider')->name('social.auth');
Route::get('auth/{provider}/callback', 'Auth\SocialAuthController@handleProviderCallback');
Auth::routes();
Route::resource('home', 'HomeController');
Route::get('/social/redirect/{provider}', 'Auth\SocialController@getSocialRedirect')->name('redirectSocialLite');
Route::get('/social/handle/{provider}', 'Auth\SocialController@getSocialHandle')->name('handleSocialLite');
Route::resource('administracion', 'AdministracionController');
Route::resource('presentacion', 'PresentacionController');
Route::resource('presComentario', 'PresComentarioController');
Route::resource('blog', 'BlogsController');
Route::resource('portada', 'PortadaController');
Route::resource('inicio', 'PortadaController');
Route::resource('blogIndex', 'BlogIndexController');
Route::post('blogIndex/store/{id}', 'BlogIndexController@store');


/*Route::get('blogIndex/show/', function(){
     
    /* Nuevo: si el argumento search está vacío regresar a la página anterior */
   
 /*   $search = urlencode(e(Input::get('titulo')));
    dd($search);
    $route = "blogIndex/show/$search";
    return redirect($route);
});*/
Route::get("blogIndex/show/", "BlogIndexController@show");
Route::get('blogIndex/pdf/{id}', 'BlogIndexController@pdf');
Route::get('blogIndex/ppt/{id}', 'BlogIndexController@ppt');
Route::get('blogIndex/docx/{id}', 'BlogIndexController@docx');
Route::get('blogIndex/xlsx/{id}', 'BlogIndexController@xlsx');
Route::get('blogIndex/video/{id}', 'BlogIndexController@video');

Route::resource('comunicacion', 'ComunicacionController');
Route::get('comunicacion/aporte/', 'ComunicacionController@aporte');

Route::resource('comunicacionIndex', 'ComunicacionIndexController');
Route::post('comunicacionIndex/store/{id}', 'ComunicacionIndexController@store');
Route::get("comunicacionIndex/show/", "ComunicacionIndexController@show");

Route::get("comunicacionIndex/content/{id}", "ComunicacionIndexController@content");

Route::resource('foro', 'ForoController');
Route::resource('comentarioForo', 'ComentarioForoController');
Route::post('comentarioForo/store/{id}', 'ComentarioForoController@store');
Route::resource('arte', 'ArteController');

Route::resource('formacion', 'FormacionController');


Route::get('/activo/',[
    'as' => 'foro.activo',
    'uses' => 'ForoController@activo'
]);

Route::get('/cerrado/',[
    'as' => 'foro.cerrado',
    'uses' => 'ForoController@cerrado'
]);
//Route::get('foro/activo/', 'ForoController@activo');

Route::resource('chat', 'ChatsController');

Route::get('/sala/',[
    'as' => 'foro.sala',
    'uses' => 'ForoController@sala'
]);

Route::post('/salachat/',[
    'as' => 'foro.store_chat',
    'uses' => 'ForoController@store_chat'
]);

Route::get('/destroy/',[
    'as' => 'comunicacionIndex.destroy',
    'uses' => 'ComunicacionIndexController@destroy'
]);

Route::get('/comunicacionIndex.administracion/',[
    'as' => 'comunicacionIndex.administracion',
    'uses' => 'ComunicacionIndexController@administracion'
]);

Route::get('/update/{id}',[
    'as' => 'foro.update',
    'uses' => 'ForoController@update'
]);

Route::resource('noticia', 'NoticiasController');

Route::get('/noticia/',[
    'as' => 'noticia.presentacion',
    'uses' => 'NoticiasController@presentacion'
]);

Route::post('/noticia/comentario/',[
    'as' => 'noticia.comentario',
    'uses' => 'NoticiasController@comentario'
]);

Route::get('/noticia/comentario/all/',[
    'as' => 'noticia.allComentario',
    'uses' => 'NoticiasController@allComentario'
]);

Route::get('/noticia/comentario/ver/{id}',[
    'as' => 'noticia.verComentario',
    'uses' => 'NoticiasController@verComentario'
]);

Route::post('/destroyComentario/{id}',[
    'as' => 'noticia.destroyComentario',
    'uses' => 'NoticiasController@destroyComentario'
]);

Route::get('/noticia.index',[
    'as' => 'noticia.index',
    'uses' => 'NoticiasController@index'
]);

Route::get('/noticia.all/',[
    'as' => 'noticia.all',
    'uses' => 'NoticiasController@all'
]);

Route::post('/update/{id}',[
    'as' => 'noticia.update',
    'uses' => 'NoticiasController@update'
]);

Route::get('/noticia.aporte/',[
    'as' => 'noticia.aporte',
    'uses' => 'NoticiasController@aporte'
]);

Route::get('/search/',[
    'as' => 'noticia.search',
    'uses' => 'NoticiasController@search'
]);

Route::get('/mis_noticias/',[
    'as' => 'noticia.mis_noticias',
    'uses' => 'NoticiasController@mis_noticias'
]);

Route::get('/edit_aporte/{id}',[
    'as' => 'noticia.edit_aporte',
    'uses' => 'NoticiasController@edit_aporte'
]);

Route::post('/updateAporte/{id}',[
    'as' => 'noticia.updateAporte',
    'uses' => 'NoticiasController@updateAporte'
]);

Route::get('noticia/pdf/{id}', 'NoticiasController@pdf');
Route::get('noticia/ppt/{id}', 'NoticiasController@ppt');
Route::get('noticia/word/{id}', 'NoticiasController@word');
Route::get('noticia/excel/{id}', 'NoticiasController@excel');
Route::get('noticia/video/{id}', 'NoticiasController@video');

Route::get('/store/{id}',[
    'as' => 'administracion.store',
    'uses' => 'AdministracionController@store'
]);

Route::get('/refreshCaptcha/',[
    'as' => 'noticia.refreshCaptcha',
    'uses' => 'NoticiasController@refreshCaptcha'
]);

Route::get('/arte/',[
    'as' => 'arte.presentacion',
    'uses' => 'ArteController@presentacion'
]);


Route::get('/index',[
    'as' => 'arte.index',
    'uses' => 'ArteController@index'
]);


Route::post('/updateArte/{id}',[
    'as' => 'arte.updateArte',
    'uses' => 'ArteController@updateArte'
]);

Route::get('/misAportes',[
    'as' => 'arte.misAportes',
    'uses' => 'ArteController@misAportes'
]);

Route::get('/ShowMusica',[
    'as' => 'arte.ShowMusica',
    'uses' => 'ArteController@ShowMusica'
]);

Route::get('/ShowDanza',[
    'as' => 'arte.ShowDanza',
    'uses' => 'ArteController@ShowDanza'
]);

Route::get('/ShowPintura',[
    'as' => 'arte.ShowPintura',
    'uses' => 'ArteController@ShowPintura'
]);

Route::get('/ShowOtros',[
    'as' => 'arte.ShowOtros',
    'uses' => 'ArteController@ShowOtros'
]);

Route::get('/ShowChistes',[
    'as' => 'arte.chistes',
    'uses' => 'ArteController@ShowChistes'
]);

Route::get('/pdf/{id}',[
    'as' => 'arte.pdf',
    'uses' => 'ArteController@pdf'
]);

Route::get('/all/',[
    'as' => 'formacion.all',
    'uses' => 'FormacionController@all'
]);

Route::get('/programa/',[
    'as' => 'formacion.programa',
    'uses' => 'FormacionController@administracion'
]);

Route::get('/formacion.aporte/',[
    'as' => 'formacion.aporte',
    'uses' => 'FormacionController@aporte'
]); 

Route::get('/formacion.area/',[
    'as' => 'formacion.area',
    'uses' => 'FormacionController@area'
]); 

Route::get('formacion/pdf/{id}', 'FormacionController@pdf');
Route::get('formacion/ppt/{id}', 'FormacionController@ppt');
Route::get('formacion/word/{id}', 'FormacionController@word');
Route::get('formacion/excel/{id}', 'FormacionController@excel');
Route::get('formacion/video/{id}', 'FormacionController@video');
Route::post('formacion/comentario/{id}', 'FormacionController@comentario');
Route::post('formacion/update/{id}', 'FormacionController@update');

Route::get('/persona/',[
    'as' => 'persona',
    'uses' => 'FormacionController@persona'
]); 
Route::get('/contexto/',[
    'as' => 'contexto',
    'uses' => 'FormacionController@contexto'
]); 
Route::get('/conocimiento/',[
    'as' => 'conocimiento',
    'uses' => 'FormacionController@conocimiento'
]); 
Route::get('/tecnologia/',[
    'as' => 'tecnologia',
    'uses' => 'FormacionController@tecnologia'
]); 
Route::get('/empresa/',[
    'as' => 'empresa',
    'uses' => 'FormacionController@empresa'
]); 

Route::resource('investigacion', 'InvestigacionsController');

Route::get('/show/',[
    'as' => 'investigacion.show',
    'uses' => 'InvestigacionsController@show'
]);

Route::get('/aporte/',[
    'as' => 'investigacion.aporte',
    'uses' => 'InvestigacionsController@aporte'
]);

app/Formacion.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Formacion extends Model
{
   protected $fillable = [
        'id','area','convocatoria','requisito','lugar','responsable','pdf','doc','excel','ppt','video','imagen','fecha_ini','fecha_fin'
    ];
}

resources/views/formacion/administracion.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        
            <div class="card">
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <div class="w3-container w3-content" style="max-width:100%;max-width:1400px;margin-top:12%">    
  <!-- The Grid -->
  <div class="w3-row">
    <!-- Left Column -->
    <div class="w3-col m3">
      <!-- Profile -->
      <div class="w3-card w3-round w3-white">


      <div class="w3-card w3-round w3-white">
        <div class="w3-container">
          
        </div>
      </div>    

      </div>
      <br>   
    <!-- End Left Column -->
    </div>
    
    <!-- Middle Column -->
    <div class="w3-col m7">
    
      <div class="w3-row-padding .w3-padding-blog">
<h6 class="w3-opacity">Programa de formacion personal</h6>
      <table class="w3-table-all">
<tr>
  <th>Fecha Inicio</th>
  <th>Fecha Fin</th>
  <th>Área</th>
</tr>
@if($programa->count())  
@foreach($programa as $programas)
<tr>
<td>{{ $programas-> fecha_ini }}</td>
<td>{{ $programas-> fecha_fin }}</td>
<td> {{ $programas-> area }}</td>
<td>{{ $programas-> created_at }}</td>
<td>
        <a class="btn btn-primary btn-xs" class="btn btn-success btn-xs" href="{{action('FormacionController@edit', $programas->id)}}" type="submit"><span class="glyphicon glyphicon-pencil">
        </span>
      </a>
    </td>
    <td>
     <form action="{{action('FormacionController@destroy', $programas->id)}}" method="POST">
      {{csrf_field()}}
        <input name="_method" type="hidden" value="DELETE">
        <button class="btn btn-danger btn-xs" type="submit"><span class="glyphicon glyphicon-trash">
        </span>
      </button>
    </td>
</tr>
@endforeach 
               @else
               <tr>
                <td colspan="8">No hay registro !!</td>
              </tr>
              @endif
</table>
{{ $programa->links() }}
      </div>
 <a href="{{ route('administracion.index') }}" class="w3-button-up" title="Messages"><span class="glyphicon glyphicon-backward">
        </span>Atrás</a>
<br>

   
    <!-- End Middle Column -->
    </div>
    
    <!-- Right Column -->
    <!-- Right Column -->
    <div class="w3-col m2">
      <div class="w3-card w3-round w3-white w3-center">
        <div class="w3-container w3-padding">
          <button type="button" class="w3-button w3-block w3-theme-l4">
            <a href="{{ route('formacion.create')}}" class="w3-button-up" title="Messages">Convocatoria por Área</a></button>
            <a href="{{ route('formacion.nueva')}}" class="w3-button-up" title="Messages">Nueva +</a></button>
          <button type="button" class="w3-button w3-block w3-theme-l4"><a href="{{ action('FormacionController@aporte')}}" class="w3-button-up" title="Messages">Mis Convocatoria</a></button>
                  <button type="button" class="w3-button w3-block w3-theme-l4"><a href="{{ action('FormacionController@presentacion')}}" class="w3-button-up" title="Messages">Presentación</a></button>

        </div>
      </div>
      <br>
    
    <!-- End Right Column -->
    </div>
    
  <!-- End Grid -->
  </div>
  
<!-- End Page Container -->
</div>
                </div>
            </div>
        
    </div>
</div>

@endsection

resources/views/formacion/aporte.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        
            <div class="card">
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <div class="w3-container w3-content" style="max-width:100%;max-width:1400px;margin-top:12%">    
  <!-- The Grid -->
  <div class="w3-row">
    <!-- Left Column -->
    <div class="w3-col m3">
      <!-- Profile -->
      <div class="w3-card w3-round w3-white">


      <div class="w3-card w3-round w3-white">
        <div class="w3-container">
          
        </div>
      </div>    

      </div>
      <br>   
    <!-- End Left Column -->
    </div>
    
    <!-- Middle Column -->
    <div class="w3-col m7">
    
      <div class="w3-row-padding .w3-padding-blog">
<h6 class="w3-opacity">Noticias y eventos</h6>
      <table class="w3-table-all">
<tr>
  <th>Titulo</th>
  <th>Carrera</th>
  <th>Entidad</th>
  <th>Fecha</th>
  <th></th>
  <th></th>
</tr>
@if($noticias->count())  
@foreach($noticias as $noticia)
<tr>
<td>{{ $noticia-> titulo }}</td>
<td> {{ $noticia-> carrera }}</td>
<td> {{ $noticia-> entidad }}</td>
<td>{{ $noticia-> created_at }}</td>
<td>
        <a class="btn btn-primary btn-xs" class="btn btn-success btn-xs" href="{{action('NoticiasController@edit', $noticia->id)}}" type="submit"><span class="glyphicon glyphicon-pencil">
        </span>
      </a>
    </td>
    <td>
     <form action="{{action('NoticiasController@destroy', $noticia->id)}}" method="POST">
      {{csrf_field()}}
        <input name="_method" type="hidden" value="DELETE">
        <button class="btn btn-danger btn-xs" type="submit"><span class="glyphicon glyphicon-trash">
        </span>
      </button>
    </td>
</tr>
@endforeach 
               @else
               <tr>
                <td colspan="8">No hay registro !!</td>
              </tr>
              @endif
</table>
{{ $noticias->links() }}
      </div>
 <a href="{{ route('noticia.all') }}" class="w3-button-up" title="Messages"><span class="glyphicon glyphicon-backward">
        </span>Atrás</a>
<br>

   
    <!-- End Middle Column -->
    </div>
    
    <!-- Right Column -->
    <!-- Right Column -->
    <div class="w3-col m2">
      <div class="w3-card w3-round w3-white w3-center">
        <div class="w3-container w3-padding">
          <button type="button" class="w3-button w3-block w3-theme-l4">
            <a href="{{ route('noticia.create')}}" class="w3-button-up" title="Messages">Nueva +</a></button>


        </div>
      </div>
      <br>
    
    <!-- End Right Column -->
    </div>
    
  <!-- End Grid -->
  </div>
  
<!-- End Page Container -->
</div>
                </div>
            </div>
        
    </div>
</div>

@endsection

resources/views/formacion/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        
            <div class="card">
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <div class="w3-container w3-content" style="max-width:100%;max-width:1400px;margin-top:12%">    
  <!-- The Grid -->
  <div class="w3-row">
    <!-- Left Column -->
    <div class="w3-col m3">
      <!-- Profile -->
      <div class="w3-card w3-round w3-white">


      <div class="w3-card w3-round w3-white">
        <div class="w3-container">
          
        </div>
      </div>    

      </div>
      <br>   
    <!-- End Left Column -->
    </div>
    
    <!-- Middle Column -->
    <div class="w3-col m7">
    
      <div class="w3-row-padding .w3-padding-blog">

      @if (count($errors) > 0)
      <div class="alert alert-danger">
        <strong>Error!</strong> Revise los campos obligatorios.<br><br>
        <ul>
          @foreach ($errors->all() as $error)
          <li>{{ $error }}</li>
          @endforeach
        </ul>
      </div>
      @endif
      @if(Session::has('success'))
      <div class="alert alert-info">
        {{Session::get('success')}}
      </div>
      @endif
          <div class="table-container">
            <form method="POST" action="{{ route('formacion.store') }}"  role="form" enctype="multipart/form-data">
              {{ csrf_field() }}
 
              <div class="form-group">
                <textarea name="convocatoria" id="convocatoria" class="form-control input-sm" placeholder="Convocatoria"></textarea>
              </div>
              <div class="form-group">
                    <textarea name="requisitos" id="requisitos" class="form-control input-sm" maxlength="2000" rows="5" placeholder="Requisitos"></textarea>
              </div>
              <p>Áreas de formación personal</p>

              {!! Form::select('area', $area, null, ['class' => 'form-control'] ) !!}
                <br>
                <p>Fecha de inicio</p>
                <div class="form-group">
                <input class="form-control input-sm" type="date" name="fecha1">
              </div>
              <p>Fecha de finalización</p>
                <div class="form-group">
                <input class="form-control input-sm" type="date" name="fecha2">
              </div>

              <div class="form-group">
                    <textarea name="lugar" id="lugar" class="form-control input-sm" maxlength="2000" rows="5" placeholder="Lugar"></textarea>
              </div>
              <div class="form-group">
                    <textarea name="responsable" id="responsable" class="form-control input-sm" maxlength="2000" rows="5" placeholder="Responsable"></textarea>
              </div>

              <br>

            <div class="form-group">
                <img width="50px" src="/img/subir_imagen.png">
                <input type="file" name="programaImg" id="programaImg" >
              </div>
              <div class="form-group">
               <img width="50px" src="/img/pdf.jpg">
                <input type="file" name="programapdf" class="form-control input-sm"  >
              </div>
              <div class="form-group">
                <img width="50px" src="/img/ppt.jpg">
                <input type="file" name="programappt" class="form-control input-sm"  >
              </div>
              <div class="form-group">
                 <img width="50px" src="/img/word.png">
                <input type="file" name="programapdfword" class="form-control input-sm"  >
              </div>
              <div class="form-group">
                <img width="50px" src="/img/excel.png">
                <input type="file" name="programapdfexcel" class="form-control input-sm"  >
              </div>
              <div class="form-group">
                <img width="50px" src="/img/video.jpg">
                <input type="file" name="programapdfvideo" class="form-control input-sm"  >
              </div>  
          <div class="row">
          <div class="col-md-4"></div>
          <div class="form-group col-md-4">
             <div class="captcha">
               <span>{!! captcha_img() !!}</span>

               </div>
            </div>
        </div>
        <div class="row">
          <div class="col-md-4"></div>
            <div class="form-group col-md-4">
             <input id="captcha" type="text" class="form-control" placeholder="Enter Captcha" name="captcha"></div>
          </div>

                <div class="col-xs-12 col-sm-12 col-md-12">
                  <input type="submit"  value="Guardar" class="btn btn-success btn-block">
                  <a href="{{ route('formacion.programa') }}" class="btn btn-info btn-block" > Atrás</a></div>
                </form>
          </div>

      </div>

<br>

   
    <!-- End Middle Column -->
    </div>
    
    <!-- Right Column -->
    <div class="w3-col m2">
      <div class="w3-card w3-round w3-white w3-center">
<div class="w3-container">
</div>
      </div>
      <br>
    
    <!-- End Right Column -->
    </div>
    
  <!-- End Grid -->
  </div>
  
<!-- End Page Container -->
</div>
                </div>
            </div>
        
    </div>
</div>

@endsection

resources/views/formacion/nueva.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        
            <div class="card">
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <div class="w3-container w3-content" style="max-width:100%;max-width:1400px;margin-top:12%">    
  <!-- The Grid -->
  <div class="w3-row">
    <!-- Left Column -->
    <div class="w3-col m3">
      <!-- Profile -->
      <div class="w3-card w3-round w3-white">


      <div class="w3-card w3-round w3-white">
        <div class="w3-container">
          <div class="pricing-table pricing-three-column row">
          <div class="w3-container"  style="padding-bottom:32px;">
          <div class="plan-name-bronze">

            <h3>Área: <i>{{ $programa->  area}}</i></h3>
            <br>

  <div class="w3-container" style="padding-bottom:32px;">
      <div class="w3-third">
        <div class="w3-row w3-center w3-card w3-padding">
        <p>Fecha Inicio:</p> <p>{{ $programa->  fecha_ini}}</p>
      </div>
      </div>

      <div class="w3-third">
      <div class="w3-row w3-center w3-card w3-padding">  
        <p>Fecha Fin:</p> <p>{{ $programa->  fecha_fin}}</p>
      </div>
      </div>
      <div class="w3-third">
        <div class="w3-row w3-center w3-card w3-padding">
        <p>Responsable:</p> <p>{{ $programa->  responsable}}</p>
      </div>
      </div>
</div>

  <div class="w3-content" style="max-width:700px">
  
    <div class="w3-row w3-center w3-card w3-padding">
      <a href="javascript:void(0)" onclick="openMenu(event, 'Eat');" id="myLink">
        <div class="w3-col s6 tablink">Convocatoria</div>
      </a>
      <a href="javascript:void(0)" onclick="openMenu(event, 'Drinks');">
        <div class="w3-col s6 tablink">Requisito</div>
      </a>
    </div>

    <div id="Eat" class="w3-container menu w3-padding-48 w3-card">
      
      <p>- La Elaboración de los textos de desarrollo de los temas del Programa de Formación Personal, así como el diseño y desarrollo de los respectivos materiales educativos virtuales demanda el concurso de escritores, investigadores, especialistas en las áreas; y expertos en la elaboracion de materiales virtuales.</p>
      <p>- Se convoca a inscribirse a dicho personal enviando una carta en la que manifieste su deseo de participar en la implementación de los temas del Programa de Formación Personal dirigido a los.</p>
    </div>

    <div id="Drinks" class="w3-container menu w3-padding-48 w3-card">
      
      <p>{{ $programa->  requisito}}</p>
    </div>  
  </div>
  <br>
<p>Lugar: {{ $programa->  lugar}}</p>

    <br>
            
          </div>

        </div>
    </div>
        </div>
      </div>    

      </div>
      <br>   
    <!-- End Left Column -->
    </div>
    
    <!-- Middle Column -->
    <div class="w3-col m7">
    
      <div class="w3-row-padding .w3-padding-blog">

      @if (count($errors) > 0)
      <div class="alert alert-danger">
        <strong>Error!</strong> Revise los campos obligatorios.<br><br>
        <ul>
          @foreach ($errors->all() as $error)
          <li>{{ $error }}</li>
          @endforeach
        </ul>
      </div>
      @endif
      @if(Session::has('success'))
      <div class="alert alert-info">
        {{Session::get('success')}}
      </div>
      @endif
          <div class="table-container">
            <form method="POST" action="{{ route('formacion.store') }}"  role="form" enctype="multipart/form-data">
              {{ csrf_field() }}
 
              <div class="form-group">
                <textarea name="convocatoria" id="convocatoria" class="form-control input-sm" placeholder="Convocatoria"></textarea>
              </div>
              <div class="form-group">
                    <textarea name="requisitos" id="requisitos" class="form-control input-sm" maxlength="2000" rows="5" placeholder="Requisitos"></textarea>
              </div>
              <p>Áreas de formación personal</p>

              {!! Form::select('area', $area, null, ['class' => 'form-control'] ) !!}
                <br>
                <p>Fecha de inicio</p>
                <div class="form-group">
                <input class="form-control input-sm" type="date" name="fecha1">
              </div>
              <p>Fecha de finalización</p>
                <div class="form-group">
                <input class="form-control input-sm" type="date" name="fecha2">
              </div>

              <div class="form-group">
                    <textarea name="lugar" id="lugar" class="form-control input-sm" maxlength="2000" rows="5" placeholder="Lugar"></textarea>
              </div>
              <div class="form-group">
                    <textarea name="responsable" id="responsable" class="form-control input-sm" maxlength="2000" rows="5" placeholder="Responsable"></textarea>
              </div>

              <br>

            <div class="form-group">
                <img width="50px" src="/img/subir_imagen.png">
                <input type="file" name="programaImg" id="programaImg" >
              </div>
              <div class="form-group">
               <img width="50px" src="/img/pdf.jpg">
                <input type="file" name="programapdf" class="form-control input-sm"  >
              </div>
              <div class="form-group">
                <img width="50px" src="/img/ppt.jpg">
                <input type="file" name="programappt" class="form-control input-sm"  >
              </div>
              <div class="form-group">
                 <img width="50px" src="/img/word.png">
                <input type="file" name="programapdfword" class="form-control input-sm"  >
              </div>
              <div class="form-group">
                <img width="50px" src="/img/excel.png">
                <input type="file" name="programapdfexcel" class="form-control input-sm"  >
              </div>
              <div class="form-group">
                <img width="50px" src="/img/video.jpg">
                <input type="file" name="programapdfvideo" class="form-control input-sm"  >
              </div>  
          <div class="row">
          <div class="col-md-4"></div>
          <div class="form-group col-md-4">
             <div class="captcha">
               <span>{!! captcha_img() !!}</span>

               </div>
            </div>
        </div>
        <div class="row">
          <div class="col-md-4"></div>
            <div class="form-group col-md-4">
             <input id="captcha" type="text" class="form-control" placeholder="Enter Captcha" name="captcha"></div>
          </div>

                <div class="col-xs-12 col-sm-12 col-md-12">
                  <input type="submit"  value="Guardar" class="btn btn-success btn-block">
                  <a href="{{ route('formacion.programa') }}" class="btn btn-info btn-block" > Atrás</a></div>
                </form>
          </div>

      </div>

<br>

   
    <!-- End Middle Column -->
    </div>
    
    <!-- Right Column -->
    <div class="w3-col m2">
      <div class="w3-card w3-round w3-white w3-center">
<div class="w3-container">
</div>
      </div>
      <br>
    
    <!-- End Right Column -->
    </div>
    
  <!-- End Grid -->
  </div>
  
<!-- End Page Container -->
</div>
                </div>
            </div>
        
    </div>
</div>

@endsection