routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Support\Facades\Route;
Route::get('/', function () {
    return view('inicio');
});
Route::get('/home', function () {
    return view('home');
});
Route::get('/administracion', function () {
    return view('administracion');
});
Route::get('/publicaciones', function () {
    return view('publicaciones');
});
Route::get('/registro', function () {
    return view('registro');
});
Route::get('/presentacion', function () {
    return view('presentacion');
});
Route::get('/portada', function () {
    return view('portada');
});

Route::get('/blogIndex', function () {
    return view('blogIndex');
});
Route::get('/comunicacionIndex', function () {
    return view('comunicacionIndex');
});

Route::get('/foro', function () {
    return view('foro.index');
});

Route::get('/chat', function () {
    return view('chat.create');
});

Route::get('/noticia.all', function () {
    return view('noticia.all');
});

Route::get('/arte', function () {
    return view('arte.presentacion');
});


Route::get('/formacion', function () {
    return view('formacion.index');
});

Route::get('/investigacion', function () {
    return view('investigacion.index');
});

Route::get('/adminv', function () {
    return view('investigacion.administracion');
});

Route::get('/encuesta', function () {
    return view('encuesta.index');
});

Route::get('/consultas', function () {
    return view('consultas.index');
});

Route::get('/convocatoria', function () {
    return view('convocatoria');
});

Route::get('/configUsu', function () {
    return view('configuracion.administracion');
});

Auth::routes();

Route::get('auth/{provider}', 'Auth\SocialAuthController@redirectToProvider')->name('social.auth');
Route::get('auth/{provider}/callback', 'Auth\SocialAuthController@handleProviderCallback');
Auth::routes();
Route::resource('home', 'HomeController');
Route::get('/social/redirect/{provider}', 'Auth\SocialController@getSocialRedirect')->name('redirectSocialLite');
Route::get('/social/handle/{provider}', 'Auth\SocialController@getSocialHandle')->name('handleSocialLite');
Route::resource('administracion', 'AdministracionController');
Route::resource('presentacion', 'PresentacionController');
Route::resource('presComentario', 'PresComentarioController');
Route::resource('blog', 'BlogsController');
Route::resource('portada', 'PortadaController');
Route::resource('inicio', 'PortadaController');
Route::resource('blogIndex', 'BlogIndexController');
Route::post('blogIndex/store/{id}', 'BlogIndexController@store');


/*Route::get('blogIndex/show/', function(){
     
    /* Nuevo: si el argumento search está vacío regresar a la página anterior */
   
 /*   $search = urlencode(e(Input::get('titulo')));
    dd($search);
    $route = "blogIndex/show/$search";
    return redirect($route);
});*/
Route::get("blogIndex/show/", "BlogIndexController@show");
Route::get('blogIndex/pdf/{id}', 'BlogIndexController@pdf');
Route::get('blogIndex/ppt/{id}', 'BlogIndexController@ppt');
Route::get('blogIndex/docx/{id}', 'BlogIndexController@docx');
Route::get('blogIndex/xlsx/{id}', 'BlogIndexController@xlsx');
Route::get('blogIndex/video/{id}', 'BlogIndexController@video');

Route::resource('comunicacion', 'ComunicacionController');
Route::get('comunicacion/aporte/', 'ComunicacionController@aporte');

Route::resource('comunicacionIndex', 'ComunicacionIndexController');
Route::post('comunicacionIndex/store/{id}', 'ComunicacionIndexController@store');
Route::get("comunicacionIndex/show/", "ComunicacionIndexController@show");

Route::get("comunicacionIndex/content/{id}", "ComunicacionIndexController@content");

Route::resource('foro', 'ForoController');
Route::resource('comentarioForo', 'ComentarioForoController');
Route::post('comentarioForo/store/{id}', 'ComentarioForoController@store');
Route::resource('arte', 'ArteController');

Route::resource('formacion', 'FormacionController');


Route::get('/activo/',[
    'as' => 'foro.activo',
    'uses' => 'ForoController@activo'
]);

Route::get('/cerrado/',[
    'as' => 'foro.cerrado',
    'uses' => 'ForoController@cerrado'
]);
//Route::get('foro/activo/', 'ForoController@activo');

Route::resource('chat', 'ChatsController');

Route::get('/sala/',[
    'as' => 'foro.sala',
    'uses' => 'ForoController@sala'
]);

Route::post('/salachat/',[
    'as' => 'foro.store_chat',
    'uses' => 'ForoController@store_chat'
]);

Route::get('/destroy/',[
    'as' => 'comunicacionIndex.destroy',
    'uses' => 'ComunicacionIndexController@destroy'
]);

Route::get('/comunicacionIndex.administracion/',[
    'as' => 'comunicacionIndex.administracion',
    'uses' => 'ComunicacionIndexController@administracion'
]);

Route::get('/update/{id}',[
    'as' => 'foro.update',
    'uses' => 'ForoController@update'
]);

Route::resource('noticia', 'NoticiasController');

Route::get('/noticia/',[
    'as' => 'noticia.presentacion',
    'uses' => 'NoticiasController@presentacion'
]);

Route::post('/noticia/comentario/',[
    'as' => 'noticia.comentario',
    'uses' => 'NoticiasController@comentario'
]);

Route::get('/noticia/comentario/all/',[
    'as' => 'noticia.allComentario',
    'uses' => 'NoticiasController@allComentario'
]);

Route::get('/noticia/comentario/ver/{id}',[
    'as' => 'noticia.verComentario',
    'uses' => 'NoticiasController@verComentario'
]);

Route::post('/destroyComentario/{id}',[
    'as' => 'noticia.destroyComentario',
    'uses' => 'NoticiasController@destroyComentario'
]);

Route::get('/noticia.index',[
    'as' => 'noticia.index',
    'uses' => 'NoticiasController@index'
]);

Route::get('/noticia.all/',[
    'as' => 'noticia.all',
    'uses' => 'NoticiasController@all'
]);

Route::post('/update/{id}',[
    'as' => 'noticia.update',
    'uses' => 'NoticiasController@update'
]);

Route::get('/noticia.aporte/',[
    'as' => 'noticia.aporte',
    'uses' => 'NoticiasController@aporte'
]);

Route::get('/search/',[
    'as' => 'noticia.search',
    'uses' => 'NoticiasController@search'
]);

Route::get('/mis_noticias/',[
    'as' => 'noticia.mis_noticias',
    'uses' => 'NoticiasController@mis_noticias'
]);

Route::get('/edit_aporte/{id}',[
    'as' => 'noticia.edit_aporte',
    'uses' => 'NoticiasController@edit_aporte'
]);

Route::post('/updateAporte/{id}',[
    'as' => 'noticia.updateAporte',
    'uses' => 'NoticiasController@updateAporte'
]);

Route::get('noticia/pdf/{id}', 'NoticiasController@pdf');
Route::get('noticia/ppt/{id}', 'NoticiasController@ppt');
Route::get('noticia/word/{id}', 'NoticiasController@word');
Route::get('noticia/excel/{id}', 'NoticiasController@excel');
Route::get('noticia/video/{id}', 'NoticiasController@video');

Route::get('/store/{id}',[
    'as' => 'administracion.store',
    'uses' => 'AdministracionController@store'
]);

Route::get('/refreshCaptcha/',[
    'as' => 'noticia.refreshCaptcha',
    'uses' => 'NoticiasController@refreshCaptcha'
]);

Route::get('/arte/',[
    'as' => 'arte.presentacion',
    'uses' => 'ArteController@presentacion'
]);


Route::get('/index',[
    'as' => 'arte.index',
    'uses' => 'ArteController@index'
]);


Route::post('/updateArte/{id}',[
    'as' => 'arte.updateArte',
    'uses' => 'ArteController@updateArte'
]);

Route::get('/misAportes',[
    'as' => 'arte.misAportes',
    'uses' => 'ArteController@misAportes'
]);

Route::get('/ShowMusica',[
    'as' => 'arte.ShowMusica',
    'uses' => 'ArteController@ShowMusica'
]);

Route::get('/ShowDanza',[
    'as' => 'arte.ShowDanza',
    'uses' => 'ArteController@ShowDanza'
]);

Route::get('/ShowPintura',[
    'as' => 'arte.ShowPintura',
    'uses' => 'ArteController@ShowPintura'
]);

Route::get('/ShowOtros',[
    'as' => 'arte.ShowOtros',
    'uses' => 'ArteController@ShowOtros'
]);

Route::get('/ShowChistes',[
    'as' => 'arte.chistes',
    'uses' => 'ArteController@ShowChistes'
]);

Route::get('/pdf/{id}',[
    'as' => 'arte.pdf',
    'uses' => 'ArteController@pdf'
]);

Route::get('/all/',[
    'as' => 'formacion.all',
    'uses' => 'FormacionController@all'
]);

Route::get('/programa/',[
    'as' => 'formacion.programa',
    'uses' => 'FormacionController@administracion'
]);

Route::get('/formacion.aporte/',[
    'as' => 'formacion.aporte',
    'uses' => 'FormacionController@aporte'
]); 

Route::get('/formacion.area/',[
    'as' => 'formacion.area',
    'uses' => 'FormacionController@area'
]); 

Route::get('formacion/pdf/{id}', 'FormacionController@pdf');
Route::get('formacion/ppt/{id}', 'FormacionController@ppt');
Route::get('formacion/word/{id}', 'FormacionController@word');
Route::get('formacion/excel/{id}', 'FormacionController@excel');
Route::get('formacion/video/{id}', 'FormacionController@video');
Route::post('formacion/comentario/{id}', 'FormacionController@comentario');
Route::post('formacion/update/{id}', 'FormacionController@update');

Route::get('/persona/',[
    'as' => 'persona',
    'uses' => 'FormacionController@persona'
]); 
Route::get('/contexto/',[
    'as' => 'contexto',
    'uses' => 'FormacionController@contexto'
]); 
Route::get('/conocimiento/',[
    'as' => 'conocimiento',
    'uses' => 'FormacionController@conocimiento'
]); 
Route::get('/tecnologia/',[
    'as' => 'tecnologia',
    'uses' => 'FormacionController@tecnologia'
]); 
Route::get('/empresa/',[
    'as' => 'empresa',
    'uses' => 'FormacionController@empresa'
]); 

Route::resource('investigacion', 'InvestigacionsController');

Route::get('/show/',[
    'as' => 'investigacion.show',
    'uses' => 'InvestigacionsController@show'
]);

Route::get('/aporte/',[
    'as' => 'investigacion.aporte',
    'uses' => 'InvestigacionsController@aporte'
]);

app/Presentacion.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Presentacion extends Model
{
    protected $fillable = ['pensamiento', 'presentacion', 'proposito','proposito2','proposito3'];
}

app/Http/Controllers/PresentacionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Presentacion;
use App\PresComentario;

class PresentacionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $presentacion=Presentacion::orderBy('id')->paginate(3);
        $presComentario=PresComentario::orderBy('id')->paginate(10);
        return view('presentacion')
        ->with('presentacion', $presentacion)
        ->with('presComentario', $presComentario);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('presentacion.presentacioncrear');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[ 'pensamiento'=>'required', 'presentacion'=>'required', 'proposito'=>'required', 'proposito2'=>'required', 'proposito3'=>'required']);
        Presentacion::create($request->all());

        return redirect()->route('presentacion')->with('success','Registro creado satisfactoriamente');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $presentacion=Presentacion::find($id);
        return  view('presentacion',compact('presentacion'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $presentacion=Presentacion::find($id);
        return view('presentacion.presentacioneditar',compact('presentacion'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[ 'pensamiento'=>'required', 'presentacion'=>'required', 'proposito'=>'required', 'proposito2'=>'required', 'proposito3'=>'required']);
 
        Presentacion::find($id)->update($request->all());
        return redirect()->route('presentacion.index')->with('success','Registro actualizado satisfactoriamente');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        PresComentario::find($id)->delete();
        return redirect()->route('presentacion.index')->with('success','Registro eliminado satisfactoriamente');
    }
    public function storecom($id)
    {
        $this->validate($request,[ 'comentarios'=>'required']);
        PresComentario::create($request->all());

        return redirect()->route('presentacion')->with('success','Registro creado satisfactoriamente');
    }

        public function storeComentario(Request $request)
    {
        $this->validate($request,[ 'comentarios'=>'required']);
 
        PresComentario::create($request->all());

        return redirect()->with('success','Registro creado satisfactoriamente');
    }

}

resources/views/presentacion/presentacioncrear.blade.php
@extends('layouts.app')

@section('content')

<!-- Navbar on small screens -->

<!-- Page Container -->
<div class="w3-container w3-content" style="max-width:100%;max-width:1400px;margin-top:8%">    
  <!-- The Grid -->
  <div class="w3-row">
    <!-- Left Column -->
    <div class="w3-col m3">
      <!-- Profile -->
      <div class="w3-card w3-round w3-white">
        <div class="w3-container">
         <h4 class="w3-center">Publicaciones Recientes</h4>
        
         <hr>
         <p><i class="fa fa-pencil fa-fw w3-margin-right w3-text-theme"></i></p>
         <p><i class="fa fa-home fa-fw w3-margin-right w3-text-theme"></i> </p>
         <p><i class="fa fa-birthday-cake fa-fw w3-margin-right w3-text-theme"></i></p>
        </div>
      </div>
      <br>
      
     
      <!-- Interests --> 
      <div class="w3-card w3-round w3-white w3-hide-small">
        <div class="w3-container">
          
        </div>
      </div>
      <br>
      
      <!-- Alert Box -->
    
    <!-- End Left Column -->
    </div>
    
    <!-- Middle Column -->
    <div class="w3-col m7">
    
      <div class="w3-row-padding">
        <div class="w3-col m12">
          <div class="w3-card w3-round w3-white">
            <div class="w3-container w3-padding">

      @if (count($errors) > 0)
      <div class="alert alert-danger">
        <strong>Error!</strong> Revise los campos obligatorios.<br><br>
        <ul>
          @foreach ($errors->all() as $error)
          <li>{{ $error }}</li>
          @endforeach
        </ul>
      </div>
      @endif
      @if(Session::has('success'))
      <div class="alert alert-info">
        {{Session::get('success')}}
      </div>
      @endif
 
        
          <div class="table-container">
            <form method="POST" action="{{ route('presentacion.store') }}"  role="form">
              {{ csrf_field() }}
 
              <div class="form-group">
                <textarea name="pensamiento" id="pensamiento" class="form-control input-sm" placeholder="Pensamiento"></textarea>
              </div>
              <div class="form-group">
                    <textarea name="presentacion" id="presentacion" class="form-control input-sm" placeholder="Presentacion"></textarea>
              </div>
              <div class="form-group">
                  <textarea name="proposito" id="proposito" class="form-control input-sm" placeholder="Proposito"></textarea>
              </div>
              
              <div class="form-group">
                  <textarea name="proposito2" id="proposito2" class="form-control input-sm" placeholder="2do Proposito"></textarea>
              </div>
              <div class="form-group">
                  <textarea name="proposito3" id="proposito3" class="form-control input-sm" placeholder="3do Proposito"></textarea>
              </div>
              <div class="form-group">
                  <input type="number" name="activo" id="activo" class="form-control input-sm"> 
              </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                  <input type="submit"  value="Guardar" class="btn btn-success btn-block">
                  <a href="" class="btn btn-info btn-block" > Atrás</a></div>
            </form>

 

          </div>
        </div>
          </div>
        </div>
        
      </div>
      
    <!-- End Middle Column -->
    </div>
    
    <!-- Right Column -->
    <div class="w3-col m2">
      <div class="w3-card w3-round w3-white w3-center">
        <div class="w3-container">
          <button type="button" class="w3-button w3-block w3-theme-l4">
            <a href="{{ url('/administracion')}}" class="w3-button-up" title="Messages">Usuarios</a></button>
          <button type="button" class="w3-button w3-block w3-theme-l4"><a href="{{ url('/presentacion')}}" class="w3-button-up" title="Messages">Presentación</a></button>
          <button type="button" class="w3-button w3-block w3-theme-l4" data-toggle="modal" data-target="#myModal">Comentarios</button>
          <button type="button" class="w3-button w3-block w3-theme-l4" data-toggle="modal" data-target="#myModal">Blog</button>
        </div>
      </div>
      <br>
    
    <!-- End Right Column -->
    </div>
    
  <!-- End Grid -->
  </div>
  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          
        </div>
        <div class="modal-body">
          


        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>
<!-- End Page Container -->
</div>
<br>
 
</html> 

resources/views/presentacion/presentacioneditar.blade.php
@extends('layouts.app')

@section('content')

<!-- Navbar on small screens -->

<!-- Page Container -->
<div class="w3-container w3-content" style="max-width:100%;max-width:1400px;margin-top:8%">    
  <!-- The Grid -->
  <div class="w3-row">
    <!-- Left Column -->
    <div class="w3-col m3">
      <!-- Profile -->
      <div class="w3-card w3-round w3-white">
        <div class="w3-container">
         <h4 class="w3-center">Publicaciones Recientes</h4>
        
         <hr>
         <p><i class="fa fa-pencil fa-fw w3-margin-right w3-text-theme"></i></p>
         <p><i class="fa fa-home fa-fw w3-margin-right w3-text-theme"></i> </p>
         <p><i class="fa fa-birthday-cake fa-fw w3-margin-right w3-text-theme"></i></p>
        </div>
      </div>
      <br>
      
     
      <!-- Interests --> 
      <div class="w3-card w3-round w3-white w3-hide-small">
        <div class="w3-container">
          
        </div>
      </div>
      <br>
      
      <!-- Alert Box -->
    
    <!-- End Left Column -->
    </div>
    
    <!-- Middle Column -->
    <div class="w3-col m7">
    
      <div class="w3-row-padding">
        <div class="w3-col m12">
          <div class="w3-card w3-round w3-white">
            <div class="w3-container w3-padding">
      @if (count($errors) > 0)
      <div class="alert alert-danger">
        <strong>Error!</strong> Revise los campos obligatorios.<br><br>
        <ul>
          @foreach ($errors->all() as $error)
          <li>{{ $error }}</li>
          @endforeach
        </ul>
      </div>
      @endif
      @if(Session::has('success'))
      <div class="alert alert-info">
        {{Session::get('success')}}
      </div>
      @endif

      <form method="POST" action="{{ route('presentacion.update',$presentacion->id) }}"  role="form">
              {{ csrf_field() }}
              <input name="_method" type="hidden" value="PATCH">
               <div class="form-group">
                <textarea name="pensamiento" class="form-control input-sm"  placeholder="pensamiento">{{$presentacion->pensamiento}}</textarea>
              </div>
              <div class="form-group">
                <textarea name="presentacion" class="form-control input-sm"  placeholder="presentacion">{{$presentacion->presentacion}}</textarea>
              </div>
              <div class="form-group">
                <textarea name="proposito" class="form-control input-sm"  placeholder="proposito">{{$presentacion->proposito}}</textarea>
              </div>
              <div class="form-group">
                <textarea name="proposito2" class="form-control input-sm"  placeholder="proposito2">{{$presentacion->proposito2}}</textarea>
              </div>
              <div class="form-group">
                <textarea name="proposito3" class="form-control input-sm"  placeholder="proposito3">{{$presentacion->proposito3}}</textarea>
              </div> 
              <div class="form-group">
              <input type="number" name="activo" id="activo" class="form-control input-sm" value="{{$presentacion->activo}}"> 
              </div>
              <div class="row">
 
                <div class="col-xs-12 col-sm-12 col-md-12">
                  <input type="submit"  value="Actualizar" class="btn btn-success btn-block">
                  <a href="" class="btn btn-info btn-block" >Atrás</a>
                </div>  
 
              </div>
            </form>



        </div>
          </div>
        </div>
        
      </div>
      
    <!-- End Middle Column -->
    </div>
    
    <!-- Right Column -->
    <div class="w3-col m2">
      <div class="w3-card w3-round w3-white w3-center">
        <div class="w3-container">
          <button type="button" class="w3-button w3-block w3-theme-l4">
            <a href="{{ url('/administracion')}}" class="w3-button-up" title="Messages">Usuarios</a></button>
          <button type="button" class="w3-button w3-block w3-theme-l4"><a href="{{ url('/presentacion')}}" class="w3-button-up" title="Messages">Presentación</a></button>
          <button type="button" class="w3-button w3-block w3-theme-l4" data-toggle="modal" data-target="#myModal">Comentarios</button>
          <button type="button" class="w3-button w3-block w3-theme-l4" data-toggle="modal" data-target="#myModal">Blog</button>
        </div>
      </div>
      <br>
    
    <!-- End Right Column -->
    </div>
    
  <!-- End Grid -->
  </div>
  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          
        </div>
        <div class="modal-body">
          


        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>
<!-- End Page Container -->
</div>
<br>
 
</html> 